package org.rpg.system;

enum state {
	TITLE_STATE,
	CUSTOMIZATION_STATE,
	OVERWORLD_STATE,
	OPTIONS_STATE,
	COMBAT_STATE,
	PARTY_MENU_STATE,
    INVENTORY_MENU_STATE,
    SAVE_GAME_STATE,
    LOAD_GAME_STATE, 
    EQUIPMENT_MENU_STATE,
	//SKILLS_MENU_STATE,
	//MAGIC_MENU_STATE,
}

